name: Build and Deploy React App

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Checkout backend repository
        uses: actions/checkout@v3
        with:
          repository: xxoocrystalxx/PersonalLibrary
          path: backend
          token: ${{ secrets.TOKEN }}

      - name: Copy build folder to backend repository
        run: |
          rm -rf backend/build
          cp -R build backend/

      - name: Commit and push changes to backend repository
        run: |
          cd backend
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Update frontend build"
          git push
